[gcp_service_account]
type = "service_account"
project_id = "quanlyduanpython"
private_key_id = "dfb6081bfd887ab44c5b8f4f4a01b86bebe0b9a3"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC...[Toàn bộ đoạn mã khóa viết liền trên 1 dòng, giữ các ký tự \n]-----\n-----END PRIVATE KEY-----\n"
client_email = "tdv2026@quanlyduanpython.iam.gserviceaccount.com"
client_id = "104406443886537574070"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/tdv2026%40quanlyduanpython.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
